### ISSUE TITLE
How to configure load paths for project?

### ISSUE THREAD

**Issue by thomthom** [castwide/vscode-solargraph#56] opened 2018-05-24 15:50 UTC
I get warnings from Solargraph that it cannot resolve my `require` statements. These are files that relate to my project. How can I tell Solargraph that paths to use to resolve `require` statements?

**Comment by castwide** [comment] 2018-05-24 16:47
How are the paths resolved at runtime? Are they part of your workspace, a required gem, etc.?

If your project uses Bundler, are you using the `solargraph.useBundler` setting? (This can fix a lot of path resolution issues, but it also requires you to add `solargraph` to your Gemfile.)

**Comment by thomthom** [comment] 2018-05-24 16:59
I write Ruby extensions for SketchUp (sketchup.com). It's a 3D modelling application with an embedded Ruby interpreter - so the scenario is slightly different from your typical  Ruby web app.

My projects typically have the extension files under a `src` directory in my project. During the development I add that to SketchUp's Ruby's `$LOAD_PATH`. (Under a regular user installation the file will be located under a Plugins directory where SketchUp is installed.)

In RubyMine I can add various paths for RM to resolve files from. I was hoping for something similar with Solargraph - if possible.

**Comment by thomthom** [comment] 2018-05-24 17:27
Ah, right. For SketchUp extensions there is no gemspec file. 

Though I have started adding a `Gemfile` in my projects, because it allows me to quickly install project dependencies for dev tools. And I can add references to a SketchUp Ruby API stubs gem which gives RubyMine insight to the SketchUp API.

I can try to see if adding a dummy gemspec file would do the trick. (Though an option would be cleaner. Let me know if I can aid in any way.)

**Comment by castwide** [comment] 2018-05-24 17:36
A dummy gemspec file is liable to work as a stopgap. Solargraph should parse it to check for `require_path` settings, even if you're not using Bundler to start the server.

I'll add configurable load paths to the roadmap.

**Comment by castwide** [comment] 2018-05-29 02:09
Support for a `require_paths` config section is in the master branch. It'll be included in gem version 0.22.0, scheduled for release tomorrow.

This is an experimental addition, so the section does not get generated when you create a new config file with the `solargraph config` command; but if you add it yourself, the server will recognize it. Example:

```
require_paths:
- src
```

**Comment by castwide** [comment] 2018-05-29 10:53
Released in gem version 0.22.0.

**Comment by thomthom** [comment] 2018-05-29 13:50
Wow! That was fast!

Just gave it a spin - it worked great for adding `src` path for my project. :D

I didn't have as much luck with adding a path outside the project path. Are the paths relative to the solargraph.yml only?

What I tried:

```
require_paths:
- "C:/Program Files/SketchUp/SketchUp 2018/Tools"
- src
```

The program files path was something I tried to add because there are some parts of the SketchUp API that require you to load files from this directory.

Also, solargraph flags `require`s from stdlib, such as `require 'json`. Would this be something that could be addressed by adding the path to the stdlib to the `yml` config? Or is there another way around that?

**Comment by castwide** [comment] 2018-05-30 01:07
Currently it assumes the path is relative to .solargraph.yml. Support for external paths is a possibility, but adds some significant complexity, e.g., the potential need to map external files. I'm still trying to determine the best way to handle additional use cases for `require` and `require_relative`.

Requires from the stdlib should work, but I just tested `json` and confirmed the issue:

```
require 'set' # This one works
require 'json' # This one does not
```

I'll look into that as well.

**Comment by thomthom** [comment] 2018-05-30 08:58
Gotcha.

While talking about external files, something that would be really nice would be to be able to provide path for stubs. The SU API for instance is defined entirely in SketchUp - immediately available. No need to `require` anything. But this leads to issues with IDEs in that they are not aware of the API methods. 
In RubyMine I solve this by adding a gem reference to API stubs: https://github.com/SketchUp/ruby-api-stubs/tree/master/SketchUp

That then is enough to provide auto-complete for the SU API.

**Comment by castwide** [comment] 2018-05-30 09:40
There are a couple of ways to make that work.

If the gem is installed on your system, Solargraph should be able to find it through a normal require, e.g., `require 'sketchup'`. You might need to run `yard gems` if its YARD documentation hasn't been generated yet.

The .solargraph.yml file has a `require` section where you can add paths that aren't explicitly required in project code.

Let me know if you still have problems.

**Comment by thomthom** [comment] 2018-05-30 10:36
The stub gem isn't actually required anywhere in the project. (I just happened to find out that adding a reference to any gem in `Gemfile` would make RubyMine process it and provide auto-complete.

The program files path I mentioned contains the only three files in the SU API where you actually need to use `require`. But for everything else (99.9% of the API) there are no require statements at all.

This `require` in `.solargraph.yml` - does it only take files? Any way to provide it with a path and have it process all files within that path? The SketchUp stub gem have quite a few files. ....unless.... maybe I can use this file... (https://github.com/SketchUp/ruby-api-stubs/blob/master/autoload/sketchup.rb)...

Let me play around with this for a bit.

**Comment by thomthom** [comment] 2018-05-30 10:58
Hmm....

I tried to tweak the stub gem to include the autoload/sketchup.rb which require all the stub files. However, after restarting Solargraph server I would not see any auto-complete for the stubs.

You mentioned that YARD docs needs to be generated. I tried `yard gems sketchup-api-stubs`, but that yields nothing. Maybe I'm missing something in my gem config? Based on this link (https://gnuu.org/2009/11/21/generate-yard-docs-for-your-gem/) I added `spec.has_rdoc      = 'yard'` to the stub gem's gemspec file. But alas - no cookie. :(

How does solargraph work for auto-complete? Does it require YARD docs to be present? Or is that just for additional details? Should it, without generated docs, show autocomplete for method/class/module names?

**Comment by castwide** [comment] 2018-05-30 12:09
Solargraph generates its own in-memory maps of the workspace code at runtime, including any YARD comments in your code. It uses generated YARD docs for external gems, since their APIs are typically stable and the implementation details can be ignored.

The issue here seems to be that Solargraph doesn't know where to find the sketchup-api-stubs YARD docs without the gem actually being installed. Right now there are three possible workarounds:

1. Install the gem on your system and generate the YARD docs.
2. Add the gem to your Gemfile, use `bundle exec yard gems` to generate the YARD docs in the repo's directory, and use Bundler to start Solargraph (the `solargraph.useBundler` option in VS Code). (This option will require `solargraph` to be in your Gemfile as well.)
3. Copy the sketchup-api-stubs code into your workspace.

As Ron Popeil would say, there's gotta be a better way. One possibility is an option to specify paths to YARD docs for inclusion in the maps. If you have an idea for a practical solution, I'm open to suggestions.

**Comment by thomthom** [comment] 2018-05-30 15:29
I have the sketchup-api-stubs gem installed globally on my system. But I have issues with the generate YARD docs part of it. `yard gems sketchup-api-stubs` just returns early. Maybe I'm messing up the doc generation for this. I've never made gems that generate YARD docs. I've only ever used YARD manually on my own libs. (Any gem package I can look at as reference to how this is implemented in a way that works with solargraph?)

**Comment by thomthom** [comment] 2018-05-30 15:58
Ah! ... it looks like it was working all along. I just had to restart VSCode. Restarting the solargraph server wasn't enough.

```
require_paths:
- "C:/Program Files/SketchUp/SketchUp 2018/Tools"
- src

require:
- sketchup-api-stubs/autoload/sketchup.rb
```

![image](https://user-images.githubusercontent.com/192418/40732192-0ee8a8fc-6433-11e8-9d63-0c45821f6e20.png)

😃

**Comment by thomthom** [comment] 2018-07-09 21:00
Is it possible to have yard docs built automatically upon installing a gem? Is that something that needs to be configured with the gem itself?

**Comment by castwide** [comment] 2018-07-11 04:14
I could have sworn there was a way to make `gem install` automatically generate YARD documentation, but I can't find it now.

Apparently the gemspec can be configured to use it, although I haven't tried it myself: https://gnuu.org/2009/11/21/generate-yard-docs-for-your-gem/

**Comment by castwide** [comment] 2018-07-26 12:20
@thomthom I happened to install YARD on a new machine, and the post-installation message said this is the command to automate gem documentation:

```
yard config --gem-install-yri
```

**Comment by thomthom** [comment] 2018-08-27 15:56
Will that generate for all installed gems?
For the stubs I'm generating I was thinking it's easier for the users if the gem itself generated YARD docs on demand. Will have to look into that.

(By the way - Solargraph rocks! So nice to be able to get RuboCop and my API stubs into VSCode.)

**Comment by castwide** [comment] 2018-08-27 17:07
Thanks!

If I understand it correctly, you have to run `yard gems` at least once for gems that are already installed, but anything you install after `yard config --gem-install-yri` should do it automatically.

I tried automating YARD generation from the language server, but it had some occasional side effects in certain setups, especially when using Bundler with gems that have `path` or `git` parameters. There might be ways to fix that. One possible solution is to make it a configuration option in the VSCode extension. In the meantime, the extension contributes palette commands to `Build new gem documentation` and `Rebuild all gem documentation`.

**Comment by thomthom** [comment] 2018-09-13 17:47
I found a way to make the gem generate the YARD database upon installation automatically: https://github.com/SketchUp/ruby-api-stubs/commit/ff3ffc1294e0ecfdc4c2446ae44ff97245cc5ddb

Adding this to my gemspec:

```
  spec.metadata = {
    'yard.run' => 'yri'
  }
```

This will generate the YARD object database that solargraph makes use of. One step less to make use of the API stubs I generate. :)

**Closed** 2018-11-12 14:53 UTC
