### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by kergrau** [castwide/vscode-solargraph#115] opened 2019-05-14 17:21 UTC
- Issue Type: `Performance`
- Extension Name: `solargraph`
- Extension Version: `0.19.6`
- OS Version: `Linux x64 4.4.0-146-generic`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/home/grau/castwide.solargraph-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by castwide** [comment] 2019-05-14 17:34
Duplicate of #109

**Comment by castwide** [comment] 2019-05-16 09:23
Just to be sure, if you can upload the `castwide.solargraph-unresponsive.cpuprofile.txt` file mentioned in your message, I might be able to confirm whether this is the same issue reported elsewhere.

**Comment by castwide** [comment] 2019-05-27 18:47
An update the improves performance is being tracked in #117. Please feel free to comment there or open a new issue if you think your problems have a different root cause.

**Closed by castwide** 2019-05-27 18:47 UTC
