### ISSUE TITLE
Errors when creating a function

### ISSUE THREAD

**Issue by garyking** [castwide/vscode-solargraph#38] opened 2018-04-06 18:28 UTC
I'm using a Mac.

I create a new file, and if I type "d", then I get the following error:

```
[Error - 14:26:16] Request completionItem/resolve failed.
  Message: Completion item could not be resolved
  Code: -32600 
```

GIF below:

![vsc-ruby](https://user-images.githubusercontent.com/343940/38438214-e2bd8014-39a7-11e8-875b-98b9eedd0639.gif)

---

If I change focus to another app then back to VSC, I get a different error:

```
[Error - 14:36:59] Request textDocument/completion failed.
  Message: Invalid offset
  Code: -32603 
```

GIF below. As you can see, it does show the snippet for `def` correctly here.

![vsc-ruby](https://user-images.githubusercontent.com/343940/38437884-d72ab146-39a6-11e8-9a2f-3a639be41263.gif)

**Comment by castwide** [comment] 2018-04-06 18:38
Confirmed.

The completionItem/resolve error should not be an error at all, since there are valid reasons for a completion item to have nothing to resolve; for example, the `def` keyword should be available as a completion items, but it doesn't have any documentation. It'll be fixed in gem version 0.18.2.

The "Invalid offset" error is more legitimate, but it probably shoudn't be sent to the client, since it usually just means that the document is in the process of being changed. I'll look for a reasonable solution.

**Comment by castwide** [comment] 2018-04-06 21:30
Gem 0.18.2 is published. It stops reporting both errors to the client.

**Comment by garyking** [comment] 2018-04-07 00:28
I can confirm it fixes it. But before the language server starts up, "def" allows me to auto-complete the function creation snippet like in my second GIF above, yet when the server starts up, it just shows me the dropdown as seen in the first GIF. 

The first method is preferable, even though the second is what I actually see most of the time.

**Comment by castwide** [comment] 2018-04-07 00:38
The snippet is still there, but it appears below case-insensitive matches, i.e., everything that starts with `d`. The same thing happens in my setup. Here are my results with the snippet selected:

![image](https://user-images.githubusercontent.com/3704922/38449226-0f406732-39da-11e8-91a8-632ea1288687.png)

You can change where snippets appear with the `editor.snippetSuggestions` setting. Valid options are `top`, `bottom`, `inline`, and `none`.

**Closed** 2018-04-07 00:53 UTC
