### ISSUE TITLE
"invalid byte sequence in US-ASCII" on latest version

### ISSUE THREAD

**Issue by garyking** [castwide/vscode-solargraph#37] opened 2018-04-05 18:21 UTC
After I open a Ruby project and use "Go to symbol in workspace", I get this in the Output panel:

```
[Error - 13:43:44] Server initialization failed.
  Message: invalid byte sequence in US-ASCII
  Code: -32603 
```

And this screenshot:

![screenshot](https://user-images.githubusercontent.com/343940/38384252-a103cb7c-38dc-11e8-9466-895ec48cdc69.png)

Needless to say, due to these errors, the extension doesn't work.

**Comment by castwide** [comment] 2018-04-06 17:46
What OS are you using? Is there a particular file that gives you this error? The most likely cause is a literal string with escaped characters, e.g., `"\xcf"`.

**Comment by garyking** [comment] 2018-04-06 18:33
I'm using a Mac. It is possible that there is a file in my workspace that is giving this error, but even if I open a blank file in the problematic workspace, and then use "Go to symbol in workspace", then the error occurs. So the extension is probably trying to index all Ruby files in my workspace, and then it comes across a problematic character. But it doesn't tell me where to look for this.

**Comment by garyking** [comment] 2018-04-06 18:53
I scanned all my files for non-ASCII characters, and found them. They are mostly emdashes (—). If I add `#encoding: utf-8` to the top of each file that contains non-ASCII characters, then Solargraph error does not occur, but "Symbols in workspace" does not show any results.

**Comment by castwide** [comment] 2018-04-06 18:54
Thanks!

The parser is supposed to handle non-ASCII characters gracefully, but there must be an exception somewhere. It's also been reported here: https://github.com/castwide/solargraph/issues/33

I haven't been able to reproduce the error on Windows, so I'm going to try again on MacOS later. At the very least, I'll modify the error so it reports which file triggered it.

**Comment by TheTharin** [comment] 2018-04-10 07:42
I'm having this issue as well. Can't just add #encoding: utf-8 to every file. That's not my own project and it won't go through code review :)

**Comment by stereoscott** [comment] 2018-04-10 18:47
I ran into this error well; would be great to see the file that caused the error. (I'm on a Mac 
```
[Error - 14:37:17] Server initialization failed.
  Message: invalid byte sequence in US-ASCII
  Code: -32603 
```
```
solargraph -v
0.18.2
```
VS Code `Version 1.22.1 (1.22.1)`, Ruby Solargraph v `0.14.1`

**Comment by castwide** [comment] 2018-04-10 19:45
This is fixed in the gem's master branch. I'll publish version 0.18.3 in the next day or so.

More information: https://github.com/castwide/solargraph/issues/33

**Comment by castwide** [comment] 2018-04-11 13:45
Version 0.18.3 is published.

**Comment by dbechrd** [comment] 2018-06-14 00:57
I'm having this issue in Solargraph `0.22.0`. It would be nice if the error could at least tell me which file contained the invalid byte sequence.

**Comment by iczman** [comment] 2018-06-19 10:13
+1 still repro with `0.22.0`

**Comment by jerrywdlee** [comment] 2018-07-11 10:32
Not the best way but effectual to me.
Just add `export LC_CTYPE=$LANG` to the `~/.bash_profile` or `~/.bashrc` and restart vscode.
Then it works.

**Comment by LeonineKing1199** [comment] 2018-08-21 15:19
I'm getting these errors as well. Which is odd because I've been using Solargraph forever and this is the first time it's had this error in a file it's opened successfully many times.

```
~ exbigboss$ solargraph -v
0.25.1
```

**Comment by castwide** [comment] 2018-08-27 17:47
Reproduced on MacOS. I'm looking into it. Any help or additional information that anyone can provide is appreciated.

**Comment by liqites** [comment] 2018-09-13 04:57
@castwide tested on vscode insider 1.28.0 with  solargraph gem version 0.27.1
problem solved

**Closed** 2018-11-12 12:54 UTC
Labels: bug, help wanted

**Comment by jaredcwhite** [comment] 2021-04-23 17:32
In case anyone find this now, I had a separate weird problem (setting up VSCode on an M1 Mac) where Solargraph+Bundler was choking on a gemspec file and throwing the "invalid byte sequence" error. Turned out I needed to add `export LANG=en_US.UTF-8` to my ~/.zshrc file and reboot VSCode, then the Solargraph extension started working. Go figure!
